---
title: "R Notebook"
output: html_notebook
---


```{r}
data_RF_activity <- data_RF %>% drop_na(XYZBreaks_sum_residuals)

set.seed(1)

data_RF_imputed_activity <- rrfImpute(XYZBreaks_sum_residuals ~ ., data_RF_activity)
target_activity <- data_RF_imputed_activity$XYZBreaks_sum_residuals
X_activity <- data_RF_imputed_activity %>% dplyr::select(-XYZBreaks_sum_residuals)

colnames(X_activity) <- compatibleNames(colnames(X_activity))
X_activity <- X_activity %>% mutate_if(is.character, compatibleNames)
```
```{r}
data_RF_imputed_activity
```

```{r}
set.seed(1313)
CM20_rf_activity <- ranger::ranger(XYZBreaks_sum_residuals ~ ., data = data_RF_imputed_activity)

CM20_rf_activity
```
```{r}
CM20_rf_activity$r.squared
```

```{r}
fread("/ebio/abt3_projects/Christensenella_CM20/Promethion/analysis_results/CM20_complete_activity_EB.txt") -> CM20_complete_activity_EB
fread("/ebio/abt3_projects/Christensenella_CM20/Promethion/analysis_results/CM20_complete_physiology.txt") -> CM20_complete_physiology
fread("/ebio/abt3_projects/Christensenella_CM20/metabolomics/CM20_targeted_metabolomics.txt") -> CM20_targeted_metabolomics
fread("/ebio/abt3_projects/Christensenella_CM20/metagenomics/CM20_pathways_endor.txt") -> CM20_pathways_endor
```
```{r}
cols_factor <- c("Sex", "Batch",  "Category")

data_RF_path <- CM20_complete_physiology %>%
  full_join(CM20_complete_activity_EB, by = "MouseID") %>%
  full_join(CM20_targeted_metabolomics, by = "MouseID") %>%
  full_join(CM20_pathways_endor, by = "MouseID")%>%
  dplyr::select(- Batch_Litter, -Promethion_Cabinet) %>% 
  dplyr::mutate_at(cols_factor, factor) %>%
  tibble::column_to_rownames(var = "MouseID")

colnames(data_RF_path) <- compatibleNames(colnames(data_RF_path))
data_RF_path <- data_RF_path %>% mutate_if(is.character, compatibleNames)
```
```{r}
set.seed(1)
data_RF_path_imputed <- rrfImpute(Category ~ ., data_RF_path)
target_path <- data_RF_path_imputed$Category
X_path <- data_RF_path_imputed %>% dplyr::select(-Category)

colnames(X_path) <- compatibleNames(colnames(X_path))
X_path <- X_path %>% mutate_if(is.character, compatibleNames)
```
#functions for classifier

```{r}
gRRFRangerCV <- function(fs_params, data, target, rf_params, covariates){
  ix <- fs_params[['ix']]
  
  #message("Feature selection")
  
  set.seed(fs_params[['gamma']]*100)
  RF <- RRF(data[ix, ], flagReg = 0, y = target[ix])
  regterm <- data.frame(Feature = rownames(RF$importance), imp = RF$importance[, 1])
  regterm$imp_norm <- (regterm$imp - min(regterm$imp))/(max(regterm$imp) - min(regterm$imp))
  regterm$lambda <- (1 - fs_params[['gamma']]) + fs_params[['gamma']] * regterm$imp_norm
  GRRF <- RRF(data[ix, ], target[ix], flagReg = 1, coefReg = regterm$lambda)
  
  #message("Subset data")
  to_keep <- colnames(data)[GRRF$feaSet]
  data <- select(data, all_of(unique(c(covariates, to_keep))))
  
  #message("RF")
  caseweights <- rep(0, length(target))
  caseweights[ix]<-1
  tmp <- lapply(rf_params, noneRanger, data = data, caseweights=caseweights, target = target)
  names(tmp) <- sapply(rf_params, paste, collapse='-ntrees_mdepth-')
  names(tmp) <- paste0("gamma-", fs_params[["gamma"]],'_',names(tmp))
  return(list('confirmed' = to_keep, 'rf_models' = tmp))
  }
```
```{r}
noneRanger <- function(data, target, params, caseweights){
  set.seed(params['num.trees']*params['max.depth'])
  rf_fs <- ranger(x = data, y = target, case.weights = caseweights, holdout = TRUE, 
  num.trees = params['num.trees'], max.depth = params['max.depth'], importance = "impurity")
  return(confusionMatrix(data = rf_fs$confusion.matrix[1:2, 1:2]))
  }
```

```{r}
# create folds
set.seed(0)
trainIx <- createDataPartition(y = target_path, times = 10, p = .8, list = TRUE)
```
```{r}
# set parameter values to test 
#gammas <- seq(0,1, by = 0.1)
#ntrees <- c(20, 50, 100, 200, 300, 400, 500, 750)
#mdepth <- seq(1,15, by = 2)

# set parameter values to the best selected parameters of the test run (accuracy of 0.8194444)
gammas <- 0.7
ntrees <- 100
mdepth <- 5
```
```{r}
rf_params_path <- as.list(data.frame(t(expand.grid(ntrees, mdepth)))) %>%
lapply(function(x){names(x) <- c('num.trees', 'max.depth');return(x)})
```
```{r}
fs_params_path <- as.list(data.frame(t(expand.grid(trainIx, gammas)))) %>%
lapply(function(x){names(x) <- c('ix', 'gamma'); return(x)})
```
```{r}
covariates <- c("Sex", "Batch")
```

```{r}
res_path <- lapply(fs_params_path, gRRFRangerCV,data= X_path, target = target_path, rf_params = rf_params_path, covariates = covariates)
```
# overall results
```{r}
tmp_path <- lapply(res_path, function(x)x$rf_models)
```
```{r}
tmp_path <- lapply(tmp_path, function(x){
res_path <- do.call(lapply(x, function(i)i$overall), what = rbind) %>% as.data.frame
res_path <- res_path %>% add_column(
  gamma = str_extract(names(x)[1], pattern = '(?<=gamma\\-).*(?=\\_[:digit:]+\\-ntrees)'), 
  mdepth = sapply(rf_params, function(y)y['max.depth']), 
  ntrees = sapply(rf_params, function(y)y['num.trees'])
  )
return(res_path)
})
```
```{r}
resCV_path <- do.call(rbind, tmp_path )
```
```{r}
resCV_path %>%
  summarise(mean(Accuracy), sd(Accuracy))
```
0.7194444 +/- 0.06860605
```{r}
resCV_path %>% group_by(gamma, mdepth, ntrees) %>%
summarise_all(mean) %>%
arrange(-Accuracy) 
```
Accuracy 0.7264323; gamma 0.7, mdepth 5, ntrees 100

```{r}
getOkModel <- function(tain_ok, params, data, target, covariates){
    ix <- tain_ok[['ix']]
  #message("Feature selection")
  
  set.seed(params['gamma']*100)
  RF <- RRF(data[ix, ], flagReg = 0, y = target[ix])
  regterm <- data.frame(Feature = rownames(RF$importance), imp = RF$importance[, 1])
  regterm$imp_norm <- (regterm$imp - min(regterm$imp))/(max(regterm$imp) - min(regterm$imp))
  regterm$lambda <- (1 - params['gamma']) + params['gamma'] * regterm$imp_norm
  GRRF <- RRF(data[ix, ], target[ix], flagReg = 1, coefReg = regterm$lambda)
  
  #message("Subset data")
  to_keep <- colnames(data)[GRRF$feaSet]
  data <- select(data, all_of(unique(c(covariates, to_keep))))
  
  #message("RF")
  caseweights <- rep(0, length(target))
  caseweights[ix]<-1
  set.seed(params['num.trees']*params['max.depth'])
  rf_fs <- ranger(x = data, y = target, case.weights = caseweights, holdout = TRUE, 
  num.trees = params['num.trees'], max.depth = params['max.depth'], importance = "impurity")
  return(rf_fs)
  }
```
```{r}
tain_ok_path <- as.list(data.frame(t(trainIx))) %>%
lapply(function(x){names(x) <- c('ix'); return(x)})
params_path = c('gamma' = 0.7, 'max.depth' = 5, 'num.trees' = 100)

importance_path <- lapply(tain_ok_path, getOkModel, data = X_path, target = target_path, params = params_path, covariates = covariates)
```
```{r}
tmp2_path <- lapply(importance_path, function(x)x$variable.importance)
tmp2_path <- lapply(tmp2_path, function(x){
importance_path <- do.call(lapply(x, function(i)i), what = rbind) %>% as.data.frame
return(importance_path)
})
importanceCV_path <- do.call(rbind, tmp2_path )

importanceCV_path.2 <- importanceCV_path %>%
  tibble::rownames_to_column(var = "var") %>%
  tidyr::separate(var, c("Resample", "feature"), sep = "\\.") %>%
  group_by(Resample) %>%
  dplyr::mutate(V1 = (V1-min(V1))/(max(V1)-min(V1))) %>%
  tidyr::spread(Resample, V1) %>%
  dplyr::mutate_all(~replace(., is.na(.), 0)) %>%
  dplyr::rowwise() %>% 
  dplyr::mutate(mean_importance = mean(c_across(Resample01:Resample10)),sd_importance = sd(c_across(Resample01:Resample10))) 

importanceCV_path.2$nr_selected <- rowSums(importanceCV_path.2[, c(-1, -12, -13)] > 0)

importanceCV_path.3<- importanceCV_path.2 %>%
  dplyr::filter(nr_selected >3) %>%
  dplyr::arrange(-mean_importance, -nr_selected) 
importanceCV_path.3
```
```{r}
n_Plus_path <- sum(data_RF_path$Category == 'Plus')
n_samp_path <- length(target_path)

samp_weight_path <- round(ifelse(data_RF_path$Category == 'Plus', 1-n_Plus_path/n_samp_path, n_Plus_path/n_samp_path), digits = 2)
```
```{r}
set.seed(1313)
CM20_rf_path <- ranger::ranger(x = X_path, y = target_path, num.trees = 100, max.depth = 5, case.weights = samp_weight_path)

CM20_rf_path
CM20_rf_path$confusion.matrix
```
```{r}
options(backup_options)
rules_loc_Plus_path <- model2DE_resampling(model = CM20_rf_path, model_type = 'ranger'
                                 , data = X_path
                                 , target = target_path, classPos = 'Plus'
                                 , times = 10
                                 , sample_weight = samp_weight
                                 , discretize = TRUE, K = 2
                                 , prune = TRUE, maxDecay = 0.05, typeDecay = 2 
                                 , filter = FALSE
                                 , in_parallel = TRUE, n_cores = 5
)
```
```{r}
alphas_Plus_path <- evaluateAlpha(rules = rules_loc_Plus_path, alphas = c(1:10), data = rules_loc_Plus_path$data, pi_thr = 0.6)
alphas_Plus_path$summary_table
```
```{r}
de_final_Plus_path <- stabilitySelection(rules = rules_loc_Plus_path, alpha_error = 3, pi_thr = 0.6)
de_final_Plus_path$rules_summary %>% subset(inN >= 6) %>% presentRules(colN = colnames(rules_loc_Plus_path$data)) %>% dplyr::arrange(-imp)
```

```{r}
options(repr.plot.width=8, repr.plot.height=3)
plotFeatures(decision_ensemble = de_final_Plus_path)
```
```{r}
options(repr.plot.width=8, repr.plot.height=5)
plotNetwork(de_final_Plus_path, hide_isolated_nodes = FALSE, layout = 'fr')+ # I usually prefer the 'fr' layout :)
scale_edge_alpha(range = c(0.8, 1))
```


